### ISSUE TITLE
Implement a "confidence score" on each thing Elvis finds

### ISSUE THREAD

**Issue by HernanRivasAcosta** [inaka/elvis#138]
The idea of a confidence score is giving a value (say, between 0 and 100) indicating how confident Elvis is that this should be looked into, where lower confidence means it's either a suggestion or that Elvis is not sure that this rule actually applies.

For a basic example, say we have the line size set to 80, having a line with 81 characters could have a confidence score of 70, while a line of 130 characters has a score of 100. The configuration file should also include the minimum value required to show a comment made by Elvis Server. Of course, this applies to all kinds of rules, if you disallow macros, a macro used only once has a confidence of 100 while a macro you used dozens of times could have a value of 90.

Pros: More informative, more natural way of handling suggestions, reduced chance of false positives.
Cons: The documentation for each rule would have to clearly describe what confidence values are to be expected and under what circumstances.

**Comment by jfacorro** [comment]
Even though this sounds like a nice idea, there is no confidence to be defined for some rules, it's either 0% or 100%.

I'm closing this  issue for now, since there has been no work associated to it for 5 years. 

Please feel free to re-open it by providing more information on how confidence should be calculated for each existing rule, so that someone can just  implement the issue.
