### ISSUE TITLE
Function Names

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#186]
We need a rule like the one we have for module names, but for function names (with a regular expression as the parameter and maybe a list of exceptions)

**Comment by kbaird** [comment]
Refer here for an exemplar: https://github.com/inaka/elvis/blob/master/src/elvis_style.erl#L151

**Comment by kbaird** [comment]
Add a file with improper function names in test_examples, make sure the new function complains appropriately.

**Comment by kbaird** [comment]
Uses [Common Test](http://www.erlang.org/doc/man/common_test.html), not EUnit.

**Comment by kbaird** [comment]
Ask here, or for more immediate feedback, http://inaka.net/hipchat

**Comment by kbaird** [comment]
I have some initial work at https://github.com/inaka/elvis/compare/master...kbaird:Issue%23186-FunctionNames. At the moment, it only covers exported functions, whereas I assume we want to try to catch bad names even for private/hidden functions, so that's my next plan.

@elbrujohalcon Do you see anything else wrong with the approach or style so far in that branch's additions that you would prefer to be changed before the final PR?

**Comment by elbrujohalcon** [comment]
It’s looking great, so far!

**Comment by kbaird** [comment]
More work in progress: https://github.com/kbaird/elvis/compare/Issue%23186-FunctionNames...kbaird:Issue%23186-FunctionNames-AlsoHidden
