### ISSUE TITLE
White output

### ISSUE THREAD

**Issue by doubleyou** [inaka/elvis#209]
Hi guys,

As a default Mac console color settings user, I find very sad that elvis prints a lot of output in white :)

Is there a way to switch to default, or at least non-background color? I can submit a pull request if we settle on some setup. (Frankly speaking, I'd make as few colors as possible and just use proper formatting that is readable enough).

Thanks!

**Comment by elbrujohalcon** [comment]
@doubleyou we would definitely appreciate a PR with some sort of `output_format :: color | plain` parameter added to elvis' configuration. You can discuss with @jfacorro where should that go exactly, most likely somewhere in the `elvis.config` file

**Comment by jfacorro** [comment]
@doubleyou I think it's a great idea to make the output a happier, colorful output :). Do you have an example on what parts of the output you would add colors to?

**Comment by elbrujohalcon** [comment]
@jfacorro I'm pretty sure he wants to **remove** the colors, not add new ones.

**Comment by jfacorro** [comment]
@elbrujohalcon I see. The default background color for OS X terminal is white and elvis is printing most text in white.

@doubleyou All output is printed using the [`elvis_utils:print/2`](https://github.com/inaka/elvis/blob/master/src/elvis_utils.erl#L161) function which in turn calls [`elvis_utils:parse_colors/1`](https://github.com/inaka/elvis/blob/master/src/elvis_utils.erl#L172). In `print` one could check the configuration value `output_format` and if `plain` then remove all `{{.*}}` in the message instead of calling `parse_colors` and replacing them with the corresponding console color format.

**Comment by doubleyou** [comment]
@jfacorro We could also make a customizable color scheme I guess, something like
```
colors => {
    success => green_bold,
    failure => red_bold,
    file_path => terminal_default,
    ...
}
```
And maybe a global switch that defaults to
```
use_colors => true
```

**Comment by elbrujohalcon** [comment]
@doubleyou that's a good idea, but I always recommend _not_ using boolean switches, so... instead of `use_colors :: boolean()` I suggested `output_format :: color | plain`. It looks more declarative, IMHO.

**Comment by doubleyou** [comment]
Yeah, sounds good. Expect a PR from me soon then :)

**Comment by elbrujohalcon** [comment]
@doubleyou any progress on this front? Should we still expect a PR from you?
