### ISSUE TITLE
Uncorrect detecting length of unicode strings 

### ISSUE THREAD

**Issue by platinumthinker** [inaka/elvis#301]
@jfacorro I use elvis from git repo (hash c0453e8)
and erlang-17. This bug repeating,
I checket with headers for unicode and without (%% -- coding: utf-8 --)
Proof - ![git@github.com:platinumthinker/elvis_unicode_fail.git](git@github.com:platinumthinker/elvis_unicode_fail.git)

**Comment by platinumthinker** [comment]
@jfacorro ping?

**Comment by jfacorro** [comment]
@platinumthinker Sorry, I haven't had time to look into this. I'm not sure when I will be able to check this out, hopefully next week.

**Comment by platinumthinker** [comment]
ok)

**Comment by platinumthinker** [comment]
@jfacorro ping?

**Comment by jfacorro** [comment]
@platinumthinker I just ran `elvis`'s version from master on the repository where this problem is exemplified and didn't get a warning concerning the line with a lot of unicode characters.

![screen shot 2015-12-04 at 10 28 51 am](https://cloud.githubusercontent.com/assets/1522569/11590832/d7036af4-9a71-11e5-8bdd-bbb708a341c6.png)

**Comment by jfacorro** [comment]
@platinumthinker I reopened the issue so you can try again running elvis and we can try to figure out your problem.

**Comment by platinumthinker** [comment]
Sorry.. I update elvis but forgot update dependency..
