### ISSUE TITLE
Rule idea: safe binary deserialization

### ISSUE THREAD

**Issue by bullno1** [inaka/elvis#306]
Unless ignored in certain module, always use `list_to_existing_atom`, `binary_to_existing_atom` and `binary_to_term/2` instead of `list_to_atom`, `binary_to_atom` and `binary_to_term/1` respectively.

Rationale: BERT is a nice binary format for RPC but the atom table can be easily exploited.

**Comment by elbrujohalcon** [comment]
:+1:

**Comment by paulo-ferraz-oliveira** [comment]
Looking at `no_common_caveats_call` I see `{erlang, size, 1}` as a default "caveat_function".

If I use only `size(A)`, in my code, does this translate to `erlang:size(A)` in the analysis' internals? If so, this new rule idea could be redundant since we could simply include those calls (`list_to_atom`, `binary_to_atom`, `binary_to_term`) in the default list.

Otherwise, if we really want to go with a different rule name, the code should be mostly code paste, shouldn't it?

**Comment by elbrujohalcon** [comment]
You're right. We can use the common caveats rule. I keep forgetting about it.
