### ISSUE TITLE
New Hex release

### ISSUE THREAD

**Issue by waisbrot** [inaka/elvis#375]
There's an `elvis` in Hex ([0.2.6-alpha3](https://hex.pm/packages/elvis/0.2.6-alpha3)), but it references a release of Katana that references a release of inaka_mixer that doesn't exist, so the whole thing is broken (😢).

**Comment by elbrujohalcon** [comment]
Yeah, the problem is that we can no longer publish things to hex.pm unless all dependencies (recursively) are published on hex.pm.
At the same time, we started migrating our repos from erlang.mk to rebar3, but for that change to start we first need to let [gadget](http://gadget.inakalabs.com) understand how to work with rebar3.
@Euen is working on that right now. Once *gadget* is ready, we'll start migrating and republishing repos one by one until we get to the point where we can publish elvis (and the other ones) again.
