### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Euen** [inaka/elvis#418]

**Comment by DBoroujerdi** [comment]
Failure is partly down to the dialyzer test. This is due to the code in test/example/pass_no_useless_seqbind.erl not compiling.

However, this is intentional as its purpose is for asserting that elvis does not warn about the use of the seqbind parse transform. As the binding are not really required for the purposes of this test a quick fix would be to remove the seqbind bindings to keep the dialyzer test happy.

And so pass_no_useless_seqbind.erl becomes,

```erlang
-module(pass_no_useless_seqbind).

-compile({parse_transformer, seqbind}).

-export([demo/0]).

demo() ->
    X1 = 10,
    X2 = X1 + 1,
    X2.
```

I've made this change in my repo and it seems to work, however, there does seem to be some remaining failures to do with lager not starting but there's a PR waiting that removes lager completely.

**Comment by ferigis** [comment]
The tests are already working
