### ISSUE TITLE
Make corrections for detected problems

### ISSUE THREAD

**Issue by vladdu** [inaka/elvis#478]
I've got a question on the [erlang/sourcer](https://github.com/erlang/sourcer/) project about integrating the code formatter with elvis. https://github.com/erlang/sourcer/issues/14

This falls in a gray zone, as I don't think the implementation would use any sourcer code, so it could just as well be part of elvis.

What is your opinion on this? 

cc: @deadtrickster

**Comment by deadtrickster** [comment]
Yep, that's one of the options, perhaps even preferred one.

**Comment by elbrujohalcon** [comment]
Hi, @vladdu @deadtrickster.

Getting elvis to auto-fix (or to recommend fixes) for the warnings it produces has been in our minds for quite a while but we never got around to actually implement it. Partially because sometimes elvis checks the source code directly, but others it checks the AST and many times a combination of both, so it easily loose track of the exact place in the source file where to apply the patch.
That's not to say it can't be done, but unless someone has *a lot* of interest and spare time to invest in this, I don't see this happening in the short term.

**Comment by jfacorro** [comment]
I don't think it should be `elvis` the one who takes care of formatting code, ideally a different formatting tool should be used in which `elvis` rules can be provided. 

Implementing this in `elvis` would make the code base really complex and therefore IMO out of scope for this tool.

**Comment by elbrujohalcon** [comment]
I agree with @jfacorro.
